name: salonguru_shop
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  collection: ^1.18.0
  dartz: ^0.10.1
  easy_localization: ^3.0.7
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  get_it: ^8.0.2
  hive: ^2.2.3
  http: ^1.2.2
  internet_connection_checker_plus: ^2.5.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  mockito: ^5.4.4
  path: ^1.8.3
  path_provider: ^2.1.5
  uuid: ^3.0.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/lang/